version: "3.8"

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
  application:
    build: .
    command: flask run --host=0.0.0.0 --port=5002
    volumes:
      - .:/application
    ports:
      - "5002:5002"
    environment:
      FLASK_APP: manage.py
      FLASK_ENV: development
    depends_on:
      - database
